module Wrapper where

import HTMLElements

-- take the first name, the last name and the nick of the portfolio, then
-- the slogan, and make a header like this below:
--
-- Dimitri 'skp' Sabadie
--       Hello, world!
header :: (String,String,String) -> String -> Tag
header (f,l,n) s = Div [header1 (f ++ " '" ++ n ++ "' " ++ l), header2 s]

-- take the name of the porfolio, the range year and make a footer
footer :: String -> (Int,Int) -> Tag
footer name (start,current) =
  Div [header4 ("(C) " ++ name ++ ", (" ++ show start ++ "-" ++ show current ++ ")"), Paragraph "Generated by Portfolio"]

-- make a navbar
navbar :: [Tag] -> Tag
navbar links = Div [ UnorderedList $ makeNavbar links ]
  where makeNavbar (a:xa) = (ListItem a) : makeNavbar xa
        makeNavbar _      = []